<?php

/**
 * @file
 * Provides a simple formatter to extract the first paragraph from the field.
 */

/**
 * Implements hook_field_formatter_info().
 */
function first_paragraph_field_formatter_info() {
  return array(
    'text_first_para' => array(
      'label' => t('First Paragraph'),
      'field types' => array('text', 'text_long', 'text_with_summary'),
    ),
  );
}


/**
 * Implements hook_field_formatter_view().
 */
function first_paragraph_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  switch ($display['type']) {
    case 'text_first_para':
      // Common case: each value is displayed individually in a sub-element
      // keyed by delta. The field.tpl.php template specifies the markup
      // wrapping each value.
      foreach ($items as $delta => $item) {
        $output = _text_sanitize($instance, $langcode, $item, 'value');
        $dom = filter_dom_load($output);

        $newdom = new DOMDocument();
        $first_para = $dom->getElementsByTagName('p')->item(0)->cloneNode(TRUE);
        $newdom->appendChild($newdom->importNode($first_para, TRUE));

        $element[$delta] = array('#markup' => $newdom->saveHTML());
      }
      break;
  }

  return $element;
}
